version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0 
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
      args:
        DISCOVERY_TYPE: single-node
    ports:
      - '9200:9200'
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - redisdata:/data
    ports:
      - '6379:6379'

  etl:
    image: python:3.10
    restart: always
    build:
      context: .
      dockerfile: ./docker/etl_docker/Dockerfile
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - ./config/.env
    command: python main.py


volumes:
  elasticdata:
  redisdata:
