version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0 
    build:
      context: ./docker/elasticsearch
      dockerfile: Dockerfile
      args:
        DISCOVERY_TYPE: single-node
    volumes:
      - elasticdata:/usr/share/elasticsearch/data

  redis:
    image: redis:6-alpine
    restart: always
    build:
      context: .
      dockerfile: ./docker/redis/Dockerfile
    volumes:
      - redisdata:/data

  etl:
    image: python:3.10
    restart: always
    build:
      context: .
      dockerfile: ./docker/etl_docker/Dockerfile
    depends_on:
      - elasticsearch
      - redis
    env_file:
      - .env
    command: python main.py


volumes:
  elasticdata:
  redisdata:
